### ISSUE TITLE
Can you release some pretrained models?

### ISSUE THREAD

**Issue by Yououko** [dechunwang/SSH-pytorch#3]
Thanks for your work. That's pretty nice.
I would like to directly test this model's speed and performance on a webcam. So is it convenient for you to share your pretrained model? Thanks in advance.

**Comment by dechunwang** [comment]
https://drive.google.com/file/d/19bmuol6CbSqL3pj9SBzUL6UhrxC3XYbC/view?usp=sharing
here is the link.
Be aware that resolution will be scaled to minimum side of 1200 by default. You should change that  setting in model/util/config.py   __C.TEST.SCALE    to your desired resolution.

**Comment by Yououko** [comment]
Thanks for your sharing, but the .zip file seems to have some problem... I could not unzip the file:
![企业微信截图_20190311171151](https://user-images.githubusercontent.com/21952030/54112294-ccf8a400-4420-11e9-95ef-3929c014d5b6.png)

If it is convenient for you, I prefer a Baidu Netdisk download link.

**Comment by dechunwang** [comment]
Hi, you do not need to unzip it. Just put this zip file under check_points folder, it will work fine.

**Comment by Yououko** [comment]
I met `RuntimeError: Error(s) in loading state_dict for SSH:
	Missing key(s) in state_dict: "conv5_128_up.bias"` when I run `test.py` without changing codes.

**Comment by dechunwang** [comment]
I forgot to commit my code. You can pull it and try it again. In the newest code, I set conv5_128_up's bias to False. In the old code, it is true. That's the reason it gives you an error.

**Comment by Yououko** [comment]
It works, thanks.
