### ISSUE TITLE
Window?

### ISSUE THREAD

**Issue by chungyau97** [dechunwang/SSH-pytorch#4]
Having trouble in running the .yml environment 
![image](https://user-images.githubusercontent.com/33013947/54909893-2afbb000-4f26-11e9-8b76-b5f6872c09ce.png)

Having trouble in running the Makefile
![image](https://user-images.githubusercontent.com/33013947/54910480-6185fa80-4f27-11e9-9996-16b3c4cc3eb1.png)

**Comment by dechunwang** [comment]
Hi,
Seems like some package in yml was outdated, so that anaconda was not able to find it.
I will update yml file and you can try it again. The makefile error was caused by the incorrect yml environment. 
You need to activate your env before `make Makefile`

**Comment by chungyau97** [comment]
@dechunwang 
.yml file still can't work. (My PC doesn't have a gpu)
C:\Users\Datasonic\Desktop\SSH\SSH-pytorch-master>conda env create -f pytorch.yml
Collecting package metadata: done
Solving environment: failed

ResolvePackageNotFound:
  - matplotlib==3.0.3=py37h5429711_0
  - pyqt==5.9.2=py37h05f1152_2
  - pyyaml==5.1=py37h7b6447c_0
  - libgcc-ng==8.2.0=hdf63c60_1
  - libgfortran-ng==7.3.0=hdf63c60_0
  - dbus==1.13.6=h746ee38_0
  - pcre==8.43=he6710b0_0
  - libopus==1.3=h7b6447c_0
  - sqlite==3.27.2=h7b6447c_0
  - libedit==3.1.20181209=hc058e9b_0
  - libglu==9.0.0=hf484d3e_1
  - freetype==2.9.1=h8a8886c_1
  - mkl==2019.3=199
  - numpy==1.16.2=py37h7e9f1db_0
  - hdf5==1.10.2=hba1933b_1
  - mkl_fft==1.0.10=py37ha843d7b_0
  - kiwisolver==1.0.1=py37hf484d3e_0
  - icu==58.2=h9c2bf20_1
  - jpeg==9b=h024ee3a_2
  - yaml==0.1.7=had09818_2
  - zlib==1.2.11=h7b6447c_3
  - libxml2==2.9.9=he19cac6_0
  - libtiff==4.0.10=h2733197_2
  - pytorch==1.0.1=cuda100py37he554f03_0
  - libstdcxx-ng==8.2.0=hdf63c60_1
  - scipy==1.2.1=py37h7c811a0_0
  - python==3.7.2=h0371630_0
  - ninja==1.9.0=py37hfd86e86_0
  - qt==5.9.7=h5867ecd_1
  - xz==5.2.4=h14c3975_4
  - graphite2==1.3.13=h23475e2_0
  - jasper==2.0.14=h07fcdf6_1
  - libxcb==1.13=h1bed415_1
  - gst-plugins-base==1.14.0=hbbd80ab_1
  - libpng==1.6.36=hbc83047_0
  - freeglut==3.0.0=hf484d3e_5
  - fontconfig==2.13.0=h9420a91_0
  - cairo==1.14.12=h8948797_3
  - libopencv==3.4.2=hb342d67_1
  - libffi==3.2.1=hd88cf55_4
  - libuuid==1.0.3=h1bed415_2
  - ffmpeg==4.0=hcdf2ecd_0
  - readline==7.0=h7b6447c_5
  - tk==8.6.8=hbc83047_0
  - cffi==1.12.2=py37h2e261b9_1
  - glib==2.56.2=hd408876_0
  - pillow==5.4.1=py37h34e0f95_0
  - bzip2==1.0.6=h14c3975_5
  - libvpx==1.7.0=h439df22_0
  - expat==2.2.6=he6710b0_0
  - zstd==1.3.7=h0b5b093_0
  - py-opencv==3.4.2=py37hb342d67_1
  - torchvision==0.2.1=py37_1
  - intel-openmp==2019.3=199
  - openssl==1.1.1b=h7b6447c_1
  - ncurses==6.1=he6710b0_1
  - sip==4.19.8=py37hf484d3e_0
  - numpy-base==1.16.2=py37hde5b4d6_0
  - tornado==6.0.1=py37h7b6447c_0
  - pixman==0.38.0=h7b6447c_0
  - gstreamer==1.14.0=hb453b48_1
  - mkl_random==1.0.2=py37hd81dba3_0
  - harfbuzz==1.8.8=hffaf4a1_0

**Comment by dechunwang** [comment]
Are you using a windows machine?  The yml file is working under ubuntu 16.04. If you want to run under windows, please install these package manually.  

python 3.0+:

pytorch
torchvision
pyymal
numpy
py-opencv
matplotlib
pillow
PIL
scipy
setuptools
cython
easydict
argparse
scikit-image

My code is written under Linux operating system, some file path in my code my not be correct.

**Comment by chungyau97** [comment]
@dechunwang 
I just need to have the proper environment listed to run test.py right? 
Because the makefile can only be run in linux
![image](https://user-images.githubusercontent.com/33013947/54965494-bec38f80-4fab-11e9-9457-d6effd7744d0.png)

**Comment by dechunwang** [comment]
You would need to change to these lines to `from model.nms.py_cpu_nms import py_cpu_nms`
 and change `return py_cpu_nms(dets, thresh)`

be warned:
NMS Speed will be much slower than native compiled code and GPU NMS (in  my case GPU NMS take 1 ms)

**Comment by chungyau97** [comment]
@dechunwang  
I can have it working in Window.. I will try using orignal script in Virtual Box linux 
In VB I should have better performance compare to windows right?
Do you have a script that draw bounding box in c2.imshow?

**Comment by dechunwang** [comment]
No,
Virtual box will not able to run cuda library.(most virtual environment do not give access to host graphics card, except docker with nvidia-docker module) You need a cuda compatible GPU in order to run on GPU.

**Comment by dechunwang** [comment]
You can modify on this code, it is pretty self-explained 
`
        img = im_data.cpu().squeeze(0).numpy()
        img = img.transpose(1, 2, 0)
        img = img[:, :, (2, 1, 0)]
        img += cfg.PIXEL_MEANS
        box_numpy =  cls_dets_single

        for i in range(box_numpy.shape[0]):
            pt1 = tuple(box_numpy[i, 0:2])
            pt2 = tuple(box_numpy[i, 2:4])
            cv2.rectangle(img, pt1, pt2, (255, i, 255 - i))
        cv2.imwrite("test/{}.jpg".format(name), img)`

**Comment by chungyau97** [comment]
> You would need to change to these lines to `from model.nms.py_cpu_nms import py_cpu_nms`
> and change `return py_cpu_nms(dets, thresh)`
> 
> be warned:
> NMS Speed will be much slower than native compiled code and GPU NMS (in my case GPU NMS take 1 ms)

What's the difference between from model.nms.py_cpu_nms import py_cpu_nms and from model.nms.cpu_nms import cpu_nms? Why can't I run the original code that you publish?

**Comment by dechunwang** [comment]
model.nms.cpu_nms is written in cython which is c-extension python, and can be compiled into machine depended low-level machine code. It is faster than interpreted python code (py_cpu_nms).  Because you are running on windows, a lot of things  are different from the Linux system.  If you run this project under ubuntu system, you will not experience that much trouble.

**Comment by chungyau97** [comment]
> You can modify on this code, it is pretty self-explained
> `
> img = im_data.cpu().squeeze(0).numpy()
> img = img.transpose(1, 2, 0)
> img = img[:, :, (2, 1, 0)]
> img += cfg.PIXEL_MEANS
> box_numpy = cls_dets_single
> 
> ```
>     for i in range(box_numpy.shape[0]):
>         pt1 = tuple(box_numpy[i, 0:2])
>         pt2 = tuple(box_numpy[i, 2:4])
>         cv2.rectangle(img, pt1, pt2, (255, i, 255 - i))
>     cv2.imwrite("test/{}.jpg".format(name), img)`
> ```

Which script contain this? 
I can't find it in test_utils.py

**Comment by chungyau97** [comment]
@dechunwang 
> You can modify on this code, it is pretty self-explained
> `
> img = im_data.cpu().squeeze(0).numpy()
> img = img.transpose(1, 2, 0)
> img = img[:, :, (2, 1, 0)]
> img += cfg.PIXEL_MEANS
> box_numpy = cls_dets_single
> 
> ```
>     for i in range(box_numpy.shape[0]):
>         pt1 = tuple(box_numpy[i, 0:2])
>         pt2 = tuple(box_numpy[i, 2:4])
>         cv2.rectangle(img, pt1, pt2, (255, i, 255 - i))
>     cv2.imwrite("test/{}.jpg".format(name), img)`
> ```
Correct me if I'm wrong.
why do we need to transpose bgr and adding back the subracted mean?
Based on this code it was done in the blob variable instead of modifying the original variable
It only did subtracting mean, and did not transpose BGR to RGB as the cnn model take BGR image
cv2.imshow I don't think we need to transpose the image into RGB (2,1,0) as cv2 take BGR (0,1,2)
![image](https://user-images.githubusercontent.com/33013947/55049591-dbcd9080-5087-11e9-94a4-a7e462df101d.png)

Without transposing and adding back the mean 
![image](https://user-images.githubusercontent.com/33013947/55049545-a4f77a80-5087-11e9-8d5d-fd77755ff03b.png)

I was able to get this result
![image](https://user-images.githubusercontent.com/33013947/55049500-74174580-5087-11e9-854f-fb76dec0e032.png)

**Comment by dechunwang** [comment]
I am glad it worked. The previous code comes from another project I am working on, I did not test on this project.

**Comment by chungyau97** [comment]
@dechunwang 
I edited the comment can you read it again? XD you reply too fast (good thing)

**Comment by chungyau97** [comment]
@dechunwang can I add you somewhere else for knowledge sharing purpose?
